Improvements

diff --git a/bin/dotenv-to-php b/bin/dotenv-to-php
--- a/bin/dotenv-to-php
+++ b/bin/dotenv-to-php
@@ -3,11 +3,8 @@
 # Ensure we are running on a clean environment.
 [ -v HOME ] && exec -c "$0" "$@"
 
-# Mark variables which are modified or created for export.
-set -a
-
-# Exit on error
-set -e
+set -a # Export vars
+set -e # Die on errors
 
 # Load dotenv file
 if [ -f "$1" ]; then source "$1"; __out="$1.php"
@@ -26,14 +23,17 @@ printf '<?php
 // Generated by dotenv-to-php
 $_DOTENV = ' > $__out
 /usr/bin/env php -r '
-	$env = array();
-	ob_start(); phpinfo(INFO_ENVIRONMENT);
-	$lines = explode("\n", trim(ob_get_clean()));
-	$ignore = array("PWD", "SHLVL", "_", "__out");
-	for($i=5, $l=count($lines); $i<$l; $i++) {
-		$parts = explode(" => ", $lines[$i], 2);
-		$env[$parts[0]] = $parts[1];
+	if (defined("PHP_VERSION_ID") && (PHP_VERSION_ID >= 70100)) $env = getenv(); 
+	else {
+		$env = array();
+		ob_start(); phpinfo(INFO_ENVIRONMENT);
+		$lines = explode("\n", trim(ob_get_clean()));
+		for($i=5, $l=count($lines); $i<$l; $i++) {
+			$parts = explode(" => ", $lines[$i], 2);
+			$env[$parts[0]] = array_key_exists($parts[0], $_SERVER) ? $_SERVER[$parts[0]] : $parts[1];
+		}
 	}
+	$ignore = array("PWD", "SHLVL", "_", "__out");
 	$env = array_diff_key($env, array_flip($ignore));
 	var_export($env);' >> $__out
 echo ';' >> $__out
